import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faEnvelope,
  faAtom,
  faFileArrowDown,
  faTrophy,
  faDiagramProject,
  faFilm,
  faNewspaper,
  faIdCard,
  faCashRegister,
  faGaugeHigh,
} from '@fortawesome/free-solid-svg-icons'
import {
  faLinkedin,
  faTelegram,
  faInstagram,
  faWhatsapp,
  faViber,
  faVuejs,
  faDev,
  faHtml5,
  faCss,
  faSass,
  faJs,
  faBootstrap,
  faGithub,
  faNodeJs,
} from '@fortawesome/free-brands-svg-icons'

library.add(
  faCashRegister,
  faGaugeHigh,
  faIdCard,
  faNewspaper,
  faFilm,
  faNodeJs,
  faDiagramProject,
  faBootstrap,
  faGithub,
  faSass,
  faJs,
  faCss,
  faHtml5,
  faTrophy,
  faFileArrowDown,
  faLinkedin,
  faTelegram,
  faInstagram,
  faWhatsapp,
  faViber,
  faEnvelope,
  faVuejs,
  faDev,
  faAtom,
)
