import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faLaptopCode,
  faEnvelope,
  faCodeCompare,
  faCodeMerge,
  faAtom,
  faBullseye,
  faFileArrowDown,
  faTrophy,
  faDiagramProject,
  faFilm,
  faNewspaper,
  faIdCard
} from '@fortawesome/free-solid-svg-icons'
import {
  faLinkedin,
  faTelegram,
  faVuejs,
  faDev,
  faHtml5,
  faCss,
  faSass,
  faJs,
  faBootstrap,
  faGithub,
  faNodeJs,
} from '@fortawesome/free-brands-svg-icons'

library.add(
  faIdCard,
  faNewspaper,
  faFilm,
  faNodeJs,
  faDiagramProject,
  faBootstrap,
  faGithub,
  faSass,
  faJs,
  faCss,
  faHtml5,
  faTrophy,
  faFileArrowDown,
  faLaptopCode,
  faLinkedin,
  faTelegram,
  faEnvelope,
  faCodeCompare,
  faVuejs,
  faDev,
  faCodeMerge,
  faAtom,
  faBullseye,
)
