import { library } from '@fortawesome/fontawesome-svg-core'
import {
  faEnvelope,
  faFileArrowDown,
  faTrophy,
  faDiagramProject,
  faNewspaper,
  faIdCard,
  faCashRegister,
  faGaugeHigh,
  faLayerGroup,
  faShieldHalved,
  faGlobe,
  faLanguage,
} from '@fortawesome/free-solid-svg-icons'
import {
  faLinkedin,
  faTelegram,
  faInstagram,
  faWhatsapp,
  faViber,
  faDev,
  faGithub,
} from '@fortawesome/free-brands-svg-icons'

library.add(
  faGlobe,
  faLanguage,
  faGithub,
  faShieldHalved,
  faLayerGroup,
  faCashRegister,
  faGaugeHigh,
  faIdCard,
  faNewspaper,
  faDiagramProject,
  faTrophy,
  faFileArrowDown,
  faLinkedin,
  faTelegram,
  faInstagram,
  faWhatsapp,
  faViber,
  faEnvelope,
  faDev,
)
